### ISSUE TITLE
This shall never be closed!

### ISSUE THREAD

**Issue by danielhickman** [xorprojects/Material-Colorize#26]

**Comment by crutchcorn** [comment]
![]()
![]()

**Comment by crutchcorn** [comment]
PS
![](http://i2.kym-cdn.com/photos/images/original/000/614/723/a09.gif)
![](http://www.reactiongifs.com/r/srcstc.gif)
![](https://31.media.tumblr.com/3840e4ad775110be9d1e8a8de6780519/tumblr_inline_n2wyhzJXN81qe4ieh.gif)
![](http://i.imgur.com/U8INyfB.gif)
![](http://www.reactiongifs.com/r/scsc.gif)
![](http://gifyu.com/images/myriah-carey-slow-clap.gif)
![](http://www.nkayesel.com/wp-content/uploads/2013/06/the-rock-slow-clap.gif)
![](http://img.pandawhale.com/post-53948-Shia-LaBeouf-Citizen-Kane-slow-Mdc4.gif)
![](http://gifsec.com/wp-content/uploads/GIF/2014/04/Slow-clap-gif.gif)
![](http://media.giphy.com/media/MjeLFmy6Lx8di/giphy.gif)
![](http://buffalopundit.com/wp-content/uploads/2014/11/slow-clap.gif)

**Comment by crutchcorn** [comment]
https://www.youtube.com/watch?v=k4UeIPxB3kM

**Comment by crutchcorn** [comment]
NO DANIEL NO

**Comment by crutchcorn** [comment]
![11138694_794639390613840_6788431116887408098_n](https://cloud.githubusercontent.com/assets/9100169/7110498/49ec923a-e167-11e4-8c69-261298a386cb.jpg)

![](http://i.imgur.com/Xx2AM2h.gif)

**Comment by crutchcorn** [comment]
[](http://media1.giphy.com/media/6L9E4acrva0Eg/giphy.gif)
[](http://media.giphy.com/media/3BR9JfSiZOp6E/giphy.gif)
[](http://media.giphy.com/media/X1Y4IHQO04VZS/giphy.gif)
