### ISSUE TITLE
Switch To Polymer

### ISSUE THREAD

**Issue by crutchcorn** [xorprojects/Material-Colorize#34]
Just adding this for reference later for myself
https://www.polymer-project.org/0.5/docs/start/tutorial/intro.html

**Comment by crutchcorn** [comment]
https://github.com/PolymerElements/polymer-starter-kit/releases

**Comment by danielhickman** [comment]
+1000

**Comment by danielhickman** [comment]
*All issues closed until we can replicate issues in Polymer* Use closed for reference only.

**Comment by crutchcorn** [comment]
Woulda wished you would've waited until we had finished the site :( Please reopen?

**Comment by danielhickman** [comment]
I mean I guess. The issues are going to get really cluttered though with Polymer

**Comment by crutchcorn** [comment]
I know
